site_name: Nikita Novikov
use_directory_urls: true

nav:
  - Главная: index.md
  - Микросервисы: microservices_usage.md

theme:
  name: null
  custom_dir: theme
extra_css:
  - 'styles.css'
extra_javascript:
  - 'script.js'

watch:
- theme
- docs