name: Deploy MkDocs Site

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install htmlmin
          pip install postcss-cli
          pip install cssmin

      - name: Build MkDocs site
        run: mkdocs build

      - name: Validate HTML
        run: |
          find ./site -name '*.html' -exec htmlhint {} \;

      - name: Minify HTML
        run: |
          find ./site -name '*.html' -exec htmlmin -o {} {} \;

      - name: Minify CSS with PostCSS
        run: |
          find ./site -name '*.css' -exec postcss {} --use autoprefixer -d ./site \;

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: github-pages
